### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by alexdhjing** [gotthardp/python-mercuryapi#1]
for the installation instruction, i tried and it showed:
```cannot find mercury module

better to run:
```python3 setup.py install
as well

**Comment by gotthardp** [comment]
Thank you. I admit the build instructions were not perfect.
I created a Makefile that automates the entire build process. Please have a look at the updated instructions in the README.md and try again. Let me know if it fails again.
I also referenced `python3 setup.py install`

**Comment by gotthardp** [comment]
Hi again. Did the fix I made solve your problem?

**Comment by alexdhjing** [comment]
Yes. It works well. Thanks!
