### ISSUE TITLE
Getting data off RFID Tags

### ISSUE THREAD

**Issue by MreowMix** [gotthardp/python-mercuryapi#10]
Hey! I got everything running, but I'm just not sure how to get the actual data off of the tags. How would you suggest about doing so?

Thanks!

**Comment by gotthardp** [comment]
Hi there! You mean how to read the user data? (As asked also in https://github.com/gotthardp/python-mercuryapi/issues/8?) That is currently not possible.

**Comment by gotthardp** [comment]
Hello. I just implemented the read access to memory banks. See the `bank` argument of the set_read_plan.
