### ISSUE TITLE
Getting TypeError: Timeout

### ISSUE THREAD

**Issue by mdjong1** [gotthardp/python-mercuryapi#100]
Getting error "TypeError: Timeout" when using ```reader = mercury.Reader("tmr:///dev/ttyUSB0", baudrate=9600)```

Not getting much else debug info; any ideas?

**Comment by mdjong1** [comment]
Looks like this is related to (TTL) connectivity issues on our end

**Comment by jacepetersen12** [comment]
@mdjong1  Just curious what issues you had. I'm having a similar problem. I can get the reader to work on my raspberry pi 3 b+ but no my Zero w. Timeout error on that same line

**Comment by mdjong1** [comment]
We ended up having issues with the USB TTL cable which was faulty. Weren't able to read from any device using any library, so finally figured out what it was.

**Comment by Headforthehills** [comment]
@jacepetersen12 Did you solve the timeout error on the zero? I too have a working project on a 3b+ that I need to run on a Pi Zero. I get the "TypeError: Timeout" on the zero only.
