### ISSUE TITLE
Missing Windows Binary Installer

### ISSUE THREAD

**Issue by bobxor** [gotthardp/python-mercuryapi#106]
At a couple points in the documentation, there is mentioning of pre-compiled binary installers.  However, it seems these are missing. 
If these exist, where are they located?
If the expectation is to build from scratch, can we remove references to the Windows Binary Installer?

Thanks!

**Comment by gotthardp** [comment]
For 0.5.1 and older there are windows installers. The 2 latest releases don't have those yet. Contributions are welcome.

**Comment by bobxor** [comment]
Okay, great.  I'll see if I can.  Thanks!
