### ISSUE TITLE
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

### ISSUE THREAD

**Issue by scottlinuxden** [gotthardp/python-mercuryapi#131]
Using Python 3.10.4 within python-mercuryapi and when you make a call to write() you get the error in the subject.  I am using an M6e micro ThingMagic USB Pro reader.  This appears to be a python 3.10 specific requirement or issue which has introduced this similar error in other python extensions.

**Comment by scottlinuxden** [comment]
Fixed the issue in this thread by performing the followin in file mercury.c

added the following line before #include <Python.h>:
#define PY_SSIZE_T_CLEAN

change the line "int data_len;" in Reader_write function to:
Py_SSIZE_t data_len;

ran make and install again to rebuild and issue no longer exists

I did not check any other functions with keywords and potential issue since I was only using read/write.

**Comment by gotthardp** [comment]
Fixed via #146
