### ISSUE TITLE
Whether to support the chip of E710？

### ISSUE THREAD

**Issue by DoongLi** [gotthardp/python-mercuryapi#139]
Hi friends，I used the reader of MKS460, Its chip is IMPINJ's E710, does the Python interface support this device?

**Comment by gotthardp** [comment]
Hello. I don't think so. The Python interface is just a wrapper for the [ThingMagic Mercury API](https://www.jadaktech.com/product/thingmagic-mercury-api/) which is developed for **JADAK ThingMagic readers**. Other readers are out of scope of this project.

**Comment by DoongLi** [comment]
ok，thx Petr

**Comment by DoongLi** [comment]
Hi Petr, by the way, Do you know if there is an ROS interface for the Impinj's E710？
