### ISSUE TITLE
Question!! How to increase the tag read range?

### ISSUE THREAD

**Issue by TinManAkshay** [gotthardp/python-mercuryapi#145]
Hi - 

I've been used this wrapper on M7E dev kit and I want to determine how to increase the tag read range. According to datasheet, it says typically over 3 meters (10ft) and I used the reader.get_power_range() function to see the max power. It says 24dB. Other than setting the power to 2400 in the function, is there any other way to possibly increase the read range?

Thanks,
Akshay

**Comment by gotthardp** [comment]
I don't know. Please ask the technical support.
