### ISSUE TITLE
Key not found error

### ISSUE THREAD

**Issue by maddy81** [gotthardp/python-mercuryapi#153]
I am running this on windows and when i am reading by 

 reader = mercury.Reader("tmr://com5",baudrate=115200,protocol = "GEN2")
 
 it says 
 
 TypeError: Key not found. I have set the baudrate to 115200 in device manager
 
 any solution for this 
 
 thanks in advance.

**Comment by giovannicanedoli** [comment]
First of all, as in the documentation you need to add an extra '/' character in your string so that your device will be correctly identified. Secondly, make sure that com5 is correctly plugged to your machine and that baudrate is correct. Hope this helps.

**Comment by maddy81** [comment]
> First of all, as in the documentation you need to add an extra '/' character in your string so that your device will be correctly identified. reader = mercury.Reader("tmr:///COM5", baudrate=115200,protocol="GEN2") Secondly, make sure that com5 is correctly plugged to your machine and that baudrate is correct. Hope this helps.

**Comment by maddy81** [comment]
Thank you soo much the issue was with the slash and when i put it it works fine. Thank you soo much.
