### ISSUE TITLE
Getting user memory data

### ISSUE THREAD

**Issue by nitayhas** [gotthardp/python-mercuryapi#19]
Hey,
Is it possible to get the user memory data?
I tried to play with the code(of mercury.c) a little bit but with no luck.

Thank you.

**Comment by gotthardp** [comment]
Hey. This feature is not yet implemented, I am afraid.

**Comment by gotthardp** [comment]
Duplicate of #8

**Comment by gotthardp** [comment]
Hello. Sorry for the delay. I just implemented the read access to memory banks. See the `bank` argument of the set_read_plan.
