### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by karimi68** [gotthardp/python-mercuryapi#2]
When I run "sudo python3 setup.py install" I end up with the following error:

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

How can I resolve the problem? (Tnx)

**Comment by gotthardp** [comment]
I am not sure. Could you please post here the messages that are printed before? Everything that is printed on the screen after you run "sudo python3 setup.py install"?

**Comment by gotthardp** [comment]
Hi again. Does the problem persists?

**Comment by dkowalsky7** [comment]
I'm having problems installing the dependencies, which I'm assuming is the problem here. I am trying use this on ubuntu and I cannot enable the repos with yum. Is there anyway to get the dependencies with sudo apt-get? Is there anyway to get the package with windows, if its not a problem

**Comment by gotthardp** [comment]
Something like `apt-get install gcc patch libxslt` should work as well. Will you please try it and tell me what happened? I have no way to test this.

**Comment by dkowalsky7** [comment]
I get

 E: unable to locate package libxslt

**Comment by gotthardp** [comment]
I see. Then please try `apt-get install gcc patch xsltproc`.

**Comment by dkowalsky7** [comment]
I was able to install that package, however I get an error from the make command at the end
![makeerror](https://cloud.githubusercontent.com/assets/20074677/17986193/87e21186-6ae7-11e6-9dbf-6be9b5fe9ece.png)

and then a get an error with setup.py

![install error](https://cloud.githubusercontent.com/assets/20074677/17986206/984da80a-6ae7-11e6-9026-84049f8c2a22.png)

**Comment by gotthardp** [comment]
Thank you very much for your patience. We are getting there slowly. There was one prerequisite missing, which is clearly my fault.

Please try `apt-get install patch xsltproc gcc libreadline-dev` and make the project again.

**Comment by dkowalsky7** [comment]
worked great! thanks for the help

**Comment by gotthardp** [comment]
I'm glad it did. Should you need anything else, just let me know.
