### ISSUE TITLE
IP address of machine where reader is connected

### ISSUE THREAD

**Issue by shreeprem4u** [gotthardp/python-mercuryapi#21]
I want to get IP address of the machine where Thingmagic reader is connected over USB port using python code. Please help me.

Thank you so much in advance

**Comment by shreeprem4u** [comment]
Can you please help me to figure it out.
I want to get IP address of system where thingmagic reader is connected over USB port.
I need to do it in Python.


Thanks in advance

**Comment by gotthardp** [comment]
Unfortunately, this is beyond my expertise. Please contact https://support.thingmagic.com/thingmagic

**Comment by shreeprem4u** [comment]
Thanks a lot for your reply
