### ISSUE TITLE
Configuring 6E Nano multiple antenna  

### ISSUE THREAD

**Issue by mundkurvenkatesh** [gotthardp/python-mercuryapi#24]
Great work writing well documented python wrapper !
I was trying to configure to read tag from multiple antenna, steps i followed are as follows
1). Since sparkfun have given access to GPIO1 of thingmagic 6E nano RFID , i have set it high to enable logical antenna 1 and 3 via antenna multiplexer. 
 
2)and also set read plan as follows, which is also mentioned in the readme.md of this repo
`reader.set_read_plan(antennas=[1,3],protocol="GEN2") `
But this throws following error 
 TypeError : Invalid antenna configuration 

What is the problem with the above steps ?

Best Regards 
mundkur

**Comment by gotthardp** [comment]
This error comes from the mercuryapi itself. I guess the numbers are wrong, or mercuryapi thinks they are wrong. What does `get_antennas` return?

**Comment by mundkurvenkatesh** [comment]
I' m checking this `reader.get_antennas()` it returns` [1]`
then i'm trying to configure antennas , that is when i get the above error. 
yea i'll surely check in mercury-api.I'm just curious as how the same python api worked for you with mercury.c api.
Thank You and Best Regards
Mundkur

**Comment by gotthardp** [comment]
If `reader.get_antennas()` returns `[1]`, then the only possible set_read_plan is `reader.set_read_plan(antennas=[1],protocol="GEN2")`. MercuryAPI does see only one antenna.

**Comment by mundkurvenkatesh** [comment]
Can we change that in MercuryApi to enable multiple antenna ?

**Comment by gotthardp** [comment]
Please ask this on the MercuryAPI list. I cannot answer this question,
