### ISSUE TITLE
Read chip temperature

### ISSUE THREAD

**Issue by WowItsDoge** [gotthardp/python-mercuryapi#26]
Hi,
it would be useful if the python api has a feature to read the chip temperature.

I think the c++ library has this feature, so maybe it is possible to support this in python too.

Regards,
Jan

**Comment by gotthardp** [comment]
I agree. Contributions are welcome :-)

**Comment by gotthardp** [comment]
Hello again. I found some time and implemented this function.

**Comment by WowItsDoge** [comment]
Thank you, this is nice!

**Comment by haroutisonfire** [comment]
Thank you for all your hard work!
