### ISSUE TITLE
Error importing mercury

### ISSUE THREAD

**Issue by JGMonroy** [gotthardp/python-mercuryapi#28]
I've ben using your code for a while, and always been able to make it work.
Today I went again to install the code in a new computer, and follow your instructions for [linux](https://github.com/gotthardp/python-mercuryapi#linux).
However, when trying to import mercury from my python code i get this error:
```
>>> import mercury
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/mercury.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/mercury.py", line 6, in __bootstrap__
ImportError: /home/username/.python-eggs/mercuryapi-0.4-py2.7-linux-x86_64.egg-tmp/mercury.so: undefined symbol: PyUnicode_AsUTF8
```

Any idea what is happening?

**Comment by JGMonroy** [comment]
It seems to be a problem with the latest mercury version.
I went back to **mercuryapi-1.29.4.34** and solve the problem. Naturally, I had the **mercuryapi-1.29.4.34.zip** file (which seems not to be available anymore on the web).

Still cannot make it work with the new **mercuryapi-1.31.0.33** that is downloaded automatically when following instructions.

**Comment by gotthardp** [comment]
Hello. And you went back with the Mercury API only, or you used some old version of the wrapper too?

**Comment by JGMonroy** [comment]
Hello. 
I copied an old installation of your wrapper (including the mercuryapi.zip) and then executed the *make* and *make install* in the new computer.

**Comment by gotthardp** [comment]
The `undefined symbol: PyUnicode_AsUTF8` is a python 2.7 compatibility issue. I made a fix for that. Please do 'git pull' to get the latest sources and try again (with the latest Mercury API zip).

**Comment by JGMonroy** [comment]
Hello.
Yes, it worked! Thanks for the fix!

**Comment by haljarrett** [comment]
This seems to be an issue once again using the most recent commit (ef5bff91acdb6f47855ea1446d1d942838a00ee6)  - replacing PyUnicode_AsUTF with PyBytes_AsString throughout mercury.c fixed it for me

**Comment by jm1024** [comment]
Confirming that this is again an issue with 0.5.3 (Ubuntu 18.04.03, Python 2.7.17) and haljarrett's fix works.
