### ISSUE TITLE
ImportError : No module name "setuptools'

### ISSUE THREAD

**Issue by haroutisonfire** [gotthardp/python-mercuryapi#31]
Hello, I'm getting an error when calling the make command. The make process ends up with the following error:

Traceback (most recent call last) : 
    File "setup.py", line 3, in <module>
      from setuptools import setup Extension
ImportError: No module named 'setuptools'
Makefile:7: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by gotthardp** [comment]
You need to install the "setuptools", e.g. via `sudo apt-get install python-setuptools`

**Comment by haroutisonfire** [comment]
Im still getting the same error

**Comment by gotthardp** [comment]
Are you using Python 2 or 3. For python 3 you need `sudo apt-get install python3-setuptools`.

**Comment by haroutisonfire** [comment]
Okay now I get fatal error: Python.h: No such file or directory 
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1 
makefile10: recipe for target 'install' failed
make: *** [install] Error 1
