### ISSUE TITLE
ImportError: No module named 'mercury'

### ISSUE THREAD

**Issue by haroutisonfire** [gotthardp/python-mercuryapi#32]
Im getting 'ImportError: No module named 'mercury' when running python test.py

**Comment by gotthardp** [comment]
The module isn't installed properly. Did you run `sudo python3 setup.py install` or `sudo make install`?

**Comment by haroutisonfire** [comment]
Fixed : It works when I run python3 test.py

**Comment by matiasz8** [comment]
Maybe you should type: "sudo make install", and then execute:

python test.py or
python3 test.py   

Try boths!

**Comment by garysenter** [comment]
I am stuck at ImportError: No module named 'mercury'.

I did the instructions for installation, then the manual instructions. and get hung up at the CD python-mercuryapi step as that directory does not exist. What am i doing wrong?

**Comment by gotthardp** [comment]
The `python-mercuryapi` directory is what you get after `https://github.com/gotthardp/python-mercuryapi.git`. If the problem persists, please open a new issue and let me know what OS you have and what exactly you did.
