### ISSUE TITLE
Multiplexer GPIO setup

### ISSUE THREAD

**Issue by haroutisonfire** [gotthardp/python-mercuryapi#33]
When a multiplexer is connected the reader.read command outputs no reads even though it would without the multiplexer. How do I set the GPIO pins high with the python wrapper? Is there anyway of this? If not, is there a way to change the built code?

**Comment by gotthardp** [comment]
Hello. The GPIO pins are not supported yet. Contributions are welcome.

**Comment by haroutisonfire** [comment]
Any ideas how to manually set this in the Mercury API build?

**Comment by gotthardp** [comment]
The API is created manually (no auto-generation), so you need to implement that function.

**Comment by gotthardp** [comment]
Done. I just implemented the functions to set and reset GPIO pins.
