### ISSUE TITLE
Key not found trying to connect a reader thought network

### ISSUE THREAD

**Issue by matiasz8** [gotthardp/python-mercuryapi#38]
Hello Gotthardp, 
thank for this project!

I've tried to use this project on a BeagleBone (ARM) with Debian. 
I'm working with Sargas hardware, with 2 antennas.

Despite I had not some packets , I could making well the project and install. 

Right now, I'm trying to connect the reader thought the network, so the uri is:

tmr://localhost
baudrate = 115200.

But, this instruction return me the message: "Key not found".

Have you any idea to how to resolv this?

Thanks a lot

**Comment by gotthardp** [comment]
\Which command gives you this? Please post here the exact parameters you use.
I am not sure network connectivity is enabled, but will test on my end.

**Comment by matiasz8** [comment]
`from __future__ import print_function
from time import sleep

try:
    import mercury
except Exception as e:
    print("Error> ", e)

class Sargas(object):

    def __init__(self):
        self.port = "localhost" #"Sargas-832f82"
        self.baud = 115200
        self.region = "NA"
        self.read_power = 1900
        self.plan = "GEN2"
        self.reader = ""

    def set_values(self):
        try:
            self.reader = mercury.Reader("tmr://" + self.port, baudrate=self.baud)
            #self.reader.set_region(self.region)
            #self.reader.set_read_plan([1], self.plan, read_power=self.read_power)
        except Exception as e:
            print("err> ", e)

    def show_values(self):
        try:
            print("Modelo: ", self.reader.get_model())
            print("Regiones soportadas", self.reader.get_supported_regions())
            print("\nRead: ", self.reader.read())
        except Exception as e:
            print("show> ", e)

    def start_read(self):
        try:
            self.reader.start_reading(lambda tag: print(tag.epc, tag.antenna, tag.read_count, tag.rssi))
            sleep(3)
            self.reader.stop_reading()
        except Exception as e:
            print("start> ", e)


if __name__ == "__main__":
    
    s = Sargas()
    s.set_values()
#    s.show_values()
#    s.start_read()`


This is my code test. I just execute:

   self.reader = mercury.Reader ("tmr: //" + self.port, baudrate = self.baud)

where "self.port" I tried with: ip / localhost / SargasName

**Comment by gotthardp** [comment]
Hello. It seems the `baudrate` argument is not allowed for network connected devices. Do just
```python
self.reader = mercury.Reader("tmr://" + self.port)
```
