### ISSUE TITLE
RSSI and Antenna ID?

### ISSUE THREAD

**Issue by BrandonPotter** [gotthardp/python-mercuryapi#4]
Is it possible to get the RSSI and Antenna ID from the tag reads?

**Comment by gotthardp** [comment]
Currently not, but I will make it possible. In few days.

**Comment by BrandonPotter** [comment]
Awesome. It looked like in BuildTagData there might just be some Mercury fields that need to go into the python tuple. Don't know if it's that easy or not...

**Comment by gotthardp** [comment]
It is quite easy, but I consider changing the tuple to an object, so you'd do `Tag.rssi` or `Tag.epc` to get the data. If a tuple gets too large it becomes messy.

**Comment by gotthardp** [comment]
Hi again. It shall work, so please check and let me know.

**Comment by BrandonPotter** [comment]
Awesome. Is it added to the tuple or changed to an obj?

**Comment by gotthardp** [comment]
It's not a tuple anymore. It's an object with (currently) 4 attributes, but it's very easy to add more. This way it is more flexible and future-proof. I hope I reflected everything in the updated README.md.

**Comment by BrandonPotter** [comment]
This works great! Thank you!
