### ISSUE TITLE
python2

### ISSUE THREAD

**Issue by karimi68** [gotthardp/python-mercuryapi#5]
Is that possible to use python2 for this python wrapper?
I am using this code in ROS Indigo, but rospy supports only python2.

**Comment by gotthardp** [comment]
It should be possible. I updated the Makefile to find the right Python version automatically. Please try it and let me know if it works.

**Comment by karimi68** [comment]
It doesn't work.
![screenshot from 2016-10-07 12 01 21](https://cloud.githubusercontent.com/assets/20804133/19202191/f4e866bc-8c85-11e6-83bb-5a79d8e327fd.png)

Based on the error I eliminated the following part of test.py (asynchronous reading mode) that I end up with the following error:

![screenshot from 2016-10-07 12 05 24](https://cloud.githubusercontent.com/assets/20804133/19202278/642726bc-8c86-11e6-91ca-21546f5f5ad3.png)

**Comment by gotthardp** [comment]
Oops, sorry. I should have tested it better. Unfortunatelly, I don't have the reader here with me.

I did two more fixes, could you please check again and let me know if there is any other error?

**Comment by karimi68** [comment]
I still got the same error.

TypeError: expecting a list of 8-bit integers

**Comment by gotthardp** [comment]
That shouldn't have happened. Sorry for asking this, but did you pull the latest version and run `make` and `make install`?

**Comment by karimi68** [comment]
Sure. Everything works properly with python3 but not 2. It's kind of weird.

**Comment by gotthardp** [comment]
Weird. I will do more tests on Monday with real hardware, but `set_read_plan` parameter parsing with Python 2 works fine here.

**Comment by karimi68** [comment]
OK. Thank you for your time. I appreciate it if you let me know the result on real hardware.

**Comment by gotthardp** [comment]
It works for me. I installed both Python 2.7 and Python 3.5, tried `test.py` on both 32-bit and 64-bit machine and it worked fine. I really suspect your error may be caused by some dependency error, which caused you don't execute the latest code.

**Comment by karimi68** [comment]
I did it over using another computer. First I got an error "fatal error: Python.h: No such file or directory" when I used "make". Then I tried the below commands to fix it:

sudo apt-get install python-dev  # for python2.x installs
sudo apt-get install python3-dev  # for python3.x installs 

Invoking these commands, the package is installed properly, and it works for python3. But, again there is an error when I try python2:
![screenshot from 2016-10-10 11 28 12](https://cloud.githubusercontent.com/assets/20804133/19246748/b8e55202-8edc-11e6-9639-102f22fe774e.png)

I am pretty sure that there is something wrong with my python2 dependencies.

**Comment by gotthardp** [comment]
The `python-dev` should be listed as a dependency. Good point.

The package was not correctly installed for Python 2. The `python setup.py install` needs to be invoked for each Python version installed. If you use `make install` you need to set the version by `make PYTHON=python install` or `make PYTHON=python3 install`. If both versions are installed, the Python3 always takes precedence and plain `make install` doesn't install Python 2.

**Comment by karimi68** [comment]
"make PYTHON=python install" solved the issue. Thank you a lot for your time.

**Comment by gotthardp** [comment]
Great! Thank you for your patience. I improved the documentation to avoid similar problems in the future.

If you need anything else, just open a new issue.
