### ISSUE TITLE
Bug start_reading

### ISSUE THREAD

**Issue by Greenerwave** [gotthardp/python-mercuryapi#55]
Hello,

I encouter an issu with the function start_reading with the folling code: 
```
import time as tm
import mercury
reader = mercury.Reader("tmr:///COM12")

    
''' paramètres'''
reader.set_read_powers([1, 2, 3, 4], [2100,2300,2200,2100])
reader.set_region("EU3")
reader.set_read_plan([1,2,3],"GEN2")
reader.set_gen2_session(0)
reader.set_gen2_q(0,2)


print("start")
reader.start_reading(lambda tag: print(tag.epc))
tm.sleep(2)
reader.stop_reading()
print("end")
```

I do not receive any error message however it forces us to restart the shell as shown in this image:
![pb lecture asynchrone](https://user-images.githubusercontent.com/48325363/53966933-7b84a800-40f4-11e9-847e-b7c9d716e9e3.PNG)

Do you have any idea how to fix it?

thank's

**Comment by gotthardp** [comment]
I haven't seen this before, but I suspect it may be a memory access problem. Could you verify it using ` valgrind --trace-children=yes ./yourscript`, please?

**Comment by Greenerwave** [comment]
thank you for your answer, I work under windows do you have another solution to offer me under windows?
Thank's

**Comment by Greenerwave** [comment]
hello,
I went from windows to Linux to check the memory access error and I used the command valgrind, I have a lot of error so if you can help me find a solution, please.
Thank's

![Capture du 2019-03-15 15-20-04](https://user-images.githubusercontent.com/48325363/54438098-4997c500-4736-11e9-92db-29cbe27333fc.png)
![Capture du 2019-03-15 15-21-05](https://user-images.githubusercontent.com/48325363/54438102-4ac8f200-4736-11e9-8d80-8323a8b5fa92.png)

**Comment by gotthardp** [comment]
Thanks for your help. Two questions:
* Did you get the crash also on Linux?
* In the list of errors that you see, is there any error that leads to the wrapper itself? I mean: at the end of each line there is a path (e.g. /usr/bin/python3.6). If you ignore all these "native" Python errors, is there any other error, which would leads to the python-mercuryapi sources?

**Comment by Greenerwave** [comment]
thanks for answering quickly,
yes you're right I think all the mistakes come from Python, it's a bit weird I thought that I have it well installed
how can I install the crash,
sorry but I do not really know Linux commands.
thank you

**Comment by Greenerwave** [comment]
I found this command:    sudo rm /var/crash/*
that's what i have to do?

Thank's

**Comment by gotthardp** [comment]
I meant whether you are experiencing the restart (you reported above) also in Linux.

The Python errors are normal, just ignore them. There is nothing wrong with your installation; I get these errors everytime. The question is whether you see something else, some error other than the Python ones.

**Comment by Greenerwave** [comment]
in fact when I increase the time sleep the reading continues and stops at a time but I do not have the display of reading stop! just the window crashes.
Thank's
![Capture du 2019-03-18 10-13-44](https://user-images.githubusercontent.com/48325363/54519321-8ea23e00-4966-11e9-9c7f-a74e394378ea.png)

**Comment by Greenerwave** [comment]
Hello,
Thank you I solved the problem it comes from our inactive python.

**Comment by gotthardp** [comment]
Cool

**Comment by SilverMecer** [comment]
> in fact when I increase the time sleep the reading continues and stops at a time but I do not have the display of reading stop! just the window crashes.
> Thank's
> ![Capture du 2019-03-18 10-13-44](https://user-images.githubusercontent.com/48325363/54519321-8ea23e00-4966-11e9-9c7f-a74e394378ea.png)

Hi, I am having the same the issue, will you please so kind and share your solution to the issue?

Thank you

**Comment by Greenerwave** [comment]
The  solution for me was to compile the programm under linux command, for
me the problem was with idle python3, so i changed the compilation method
with this command (python3 test.py).



Fatima-ezzahraa Majid
+33 7 69 14 37 02



Le jeu. 18 avr. 2019 à 08:11, SilverMecer <notifications@github.com> a
écrit :
