### ISSUE TITLE
pip install fails on Raspberry Pi

### ISSUE THREAD

**Issue by romainrobotics** [gotthardp/python-mercuryapi#56]
I'm not sure how pip works in terms of installing dependencies before installing the target library, but some necessary dependencies are apparently not present in Raspbian. Simply running 

pip2 install python-mercuryapi 

will fail unless first running 

sudo apt-get install patch xsltproc gcc libreadline-dev python-dev python-setuptools

Like I wrote, I don't know how pip works but I thought it was possible to build in the installation of dependencies first, so maybe that could be added in.

**Comment by gotthardp** [comment]
I don't think it is possible to specify OS dependencies in the pip file. But I will at least update the documentation. Thanks.

**Comment by gotthardp** [comment]
Documented already.
