### ISSUE TITLE
TagReadData Object RSSI average?

### ISSUE THREAD

**Issue by mitchgalea** [gotthardp/python-mercuryapi#57]
Hello,

Just wondering whether the rssi value returned in TagReadData objects from reader.read() when read_count > 1 is the average rssi value of all the readings or something else such as the last rssi value?

**Comment by gotthardp** [comment]
Good question, but this is a MercuryAPI feature. The [documentation](https://www.jadaktech.com/wp-content/uploads/2018/02/MercuryAPI_ProgrammerGuide_for_v1.27.3.pdf) says it is controlled by the `/reader/tagReadData/recordHighestRssi` parameter, which is not configurable from Python. Default depends on your reader, so I cannot be more specific.
