### ISSUE TITLE
Key error when try to connect a reader throught network

### ISSUE THREAD

**Issue by rafanimal** [gotthardp/python-mercuryapi#6]
Hi, when I try to connect the reader I get a message saying: "Key Error". In the previous version I could connect without problems. How do I connect a reader that is on a network, not connected to the computer? In the old version, i use the command: mercury.Reader("tmr://m6-2128e5"), but doesn't work anymore.

**Comment by gotthardp** [comment]
Oops, my fault. Sorry. I made a fix that should make it work again. Please check and let me know.

**Comment by rafanimal** [comment]
Wow! Thank you so much! Working perfect now!
