### ISSUE TITLE
Real time inventory time

### ISSUE THREAD

**Issue by Greenerwave** [gotthardp/python-mercuryapi#63]
hello!
do you have a solution to set the inventory time for a duration for asynchronous read?

THANKS

**Comment by gotthardp** [comment]
I am not sure I understand. What is "inventory time", please?

**Comment by Greenerwave** [comment]
the number of times of calling the reader.start.reading function

**Comment by gotthardp** [comment]
You shall call it once to start the reading. The reading then usually continues for a long time. The async read had no duration.
