### ISSUE TITLE
Unable to change the HopTime and HopTable

### ISSUE THREAD

**Issue by BoomerIsSpartacus** [gotthardp/python-mercuryapi#64]
I have searched through the documents and saw that there is a parameter that can be used to change the Hoptime and hoptable but that there is no object created for these parameters. Do I understand it correctly, thus making it impossible to change these parameters in python using this api ? Is it possible to add this funtionality and if so how do one go about adding this?

**Comment by gotthardp** [comment]
I just implemented it.
