### ISSUE TITLE
Segmentation Fault on long asynchronous reading (start_reading())

### ISSUE THREAD

**Issue by Jack839** [gotthardp/python-mercuryapi#65]
I have found a new issue which actually give segmentation fault on long asynchronous reading.
After reading continously around 60000 times in total with may tags it returns segmentation fault.
I have attached a image which was the problem that api gave on debugginging with gdb.
![IMG_20190611_145650__01](https://user-images.githubusercontent.com/22985126/59425552-cac52d80-8df3-11e9-88da-1c999208e033.jpg)

There was a same kind of issue reported previously here: [https://github.com/gotthardp/python-mercuryapi/issues/58](url) but the workaround provided there doesnt help me as i am trying to build a gui using this api and time.sleep is blocking my gui and also when i tried this doing all this in a thread. It also lagged my gui as thread and asynchronous reading is giving their own problem about which i don't have a clue about. Kindly help me.

After somemore tries it shows this error which is quite same but more detailed:
![image](https://user-images.githubusercontent.com/22985126/59431441-94db7580-8e02-11e9-8217-92cafacea60b.png)
NOTE: This build of mercury api is before shuffling of functions commit.

**Comment by gotthardp** [comment]
Could you try displaying `bt` in gdb? This is too little information to debug something.

**Comment by Jack839** [comment]
I will show it you soon.

**Comment by Jack839** [comment]
backtraced: 
![image](https://user-images.githubusercontent.com/22985126/59488801-264bf580-8e9e-11e9-87b1-a5ace795df3b.png)

**Comment by gotthardp** [comment]
I made an update that could possibly fix the error. Could you please try and let me know if it helped?

**Comment by Jack839** [comment]
Will try and tell you.

**Comment by Jack839** [comment]
Looks like this is solved. I read around 1.2 lakhs times without any issue.
