### ISSUE TITLE
GPIO Pins implementation

### ISSUE THREAD

**Issue by Jack839** [gotthardp/python-mercuryapi#66]
Is there any way to get the gpio pins working of the reader? 
Because I really need them for a project. If you can do it, it would be very nice or else you might teach me or tell me the resources to learn how to implement c api features for python?

Thank you sir

**Comment by gotthardp** [comment]
Duplicate of #33.

I will implement it.

**Comment by Jack839** [comment]
Okay Sir, thank you .

**Comment by gotthardp** [comment]
Done. (I am extremely fast today :) )

**Comment by Jack839** [comment]
Yipee....thank you sir

**Comment by Jack839** [comment]
Can you still teach me how to implement any new functionality in the library?

**Comment by gotthardp** [comment]
Have a look how the GPIO is done. It's in one quite clean commit:
https://github.com/gotthardp/python-mercuryapi/commit/58e28774844a8aae1543bcbab452ea41627dd9c8

**Comment by Jack839** [comment]
Okay sir, I will check it out.
