### ISSUE TITLE
reader.gpo_set(2, False) is not working.

### ISSUE THREAD

**Issue by Jack839** [gotthardp/python-mercuryapi#67]
Here is the error:
![image](https://user-images.githubusercontent.com/22985126/59492211-19cb9b00-8ea6-11e9-90f9-d739c246fddf.png)
Other function of gpio is working fine.

**Comment by gotthardp** [comment]
Does `reader.get_gpio_outputs()` include the pin you want to set?

**Comment by Jack839** [comment]
When this code was ran:
`print("GPIO Inputs:", reader.get_gpio_inputs())
print("GPIO Outputs:", reader.get_gpio_outputs())
#reader.gpo_set(2, False)
print("GPI GET:", reader.gpi_get(2))
reader.set_gpio_inputs([1, 2])
print("GPIO Inputs:", reader.get_gpio_inputs())
reader.set_gpio_outputs([3, 4])
print("GPIO Outputs:",reader.get_gpio_outputs())`
Output:
![image](https://user-images.githubusercontent.com/22985126/59497110-674d0580-8eb0-11e9-93e6-75c048feb5fa.png)

**Comment by gotthardp** [comment]
Looks good, or? The gpo_set shall be called **after** you clear the pin from gpio_inputs.

**Comment by Jack839** [comment]
Will try and tell you.

**Comment by Jack839** [comment]
It is working fine after doing that but is it supposed to stay stuck at that line for keeping the gpio pin high? Because code is stuck at that line and not proceeding further.

**Comment by gotthardp** [comment]
What is the call-stack when you interrupt the script by ctrl-c?

**Comment by Jack839** [comment]
It is working fine sir. It was my mistake.
