### ISSUE TITLE
Writing data to tags

### ISSUE THREAD

**Issue by NicolasE124** [gotthardp/python-mercuryapi#68]
Hello,

I would like to write data on my tags. From what I see the reader.write function only allows to change the EPC. Is there a way to write on a different bank of the tag or is it not implemented in the wrapper yet?
Kind regards

**Comment by gotthardp** [comment]
Hello. I am afraid that only the EPC can be written at this moment.

**Comment by NicolasE124** [comment]
Thanks for your quick answer! Although it is not the one I was hoping for :)
Is there a way to implement it myself (knowing that I am not really an expert in C)? If you have any doc on the method used for other functions that would be much appreciated. In the meantime I will have a closer look at your code see if I can get some understanding.
Regards

**Comment by gotthardp** [comment]
What exactly you want to write to the tag?

**Comment by NicolasE124** [comment]
So, I am trying to play with some NXP RFID microchip which has 2 RF ports (https://www.nxp.com/docs/en/data-sheet/SL3S4011_4021.pdf). From what I can see there is a specific place in the EPC bank which allows to select which RF port is active. I would like to be able to modify that. Thanks again

**Comment by gotthardp** [comment]
I've added `read_tag_mem` and `write_tag_mem` functions, which is probably what you need.

**Comment by NicolasE124** [comment]
That is awesome, I'll give it a go asap
Thanks a lot for the support!

**Comment by gotthardp** [comment]
I am glad it works :)

**Comment by Bo-Bo-Han** [comment]
> Hello. I am afraid that only the EPC can be written at this moment.
