### ISSUE TITLE
Support for Gen2 Settings

### ISSUE THREAD

**Issue by wmcmahanBG** [gotthardp/python-mercuryapi#7]
Nice work on the code.  I've been able to use it to get some initial reads with a ThingMagic Sargas UHF reader.  I was wondering if you had any plans on adding support for gen2 settings (e.g. tari, BLF, session).

Thanks!

**Comment by gotthardp** [comment]
Thank you. Unfortunately, I don't have enough time do implement this now. Volunteers are welcome ;-)
