### ISSUE TITLE
Temperature reading while asynchronous reading of tag not allowed.

### ISSUE THREAD

**Issue by Jack839** [gotthardp/python-mercuryapi#71]
Current I am trying to read temp and tag reading simultaneously but doing that gives error as "error getting temperature". Is it possible somehow? I think this feature is there in the c api.

**Comment by gotthardp** [comment]
I just made an update that will improve the error report. It will not solve your problem, but the error report will be more specific and perhaps it will clarify what is wrong.

**Comment by Jack839** [comment]
Now it shows this error: `RuntimeError: Unimplemented feature`

**Comment by gotthardp** [comment]
This is coming directly from your reader, so it does not support it.

**Comment by Jack839** [comment]
okay sir.

**Comment by gotthardp** [comment]
New function `enable_stats` was just introduced to address this. https://github.com/gotthardp/python-mercuryapi/commit/7f493198056824cba9f8b11e89eadf46c4720de2
