### ISSUE TITLE
Timing issues

### ISSUE THREAD

**Issue by NicolasE124** [gotthardp/python-mercuryapi#72]
Hello

I am using multiple synchronous reads to realise inventories and I realised it was taking longer than expected. For example, using the time.time functions for 50 inventories of 100ms each, the time.time() gives me  about 9.5s (instead of 5s). It is even worse for shorter inventories (50 times 50ms actually takes 7.5 seconds). I realise there might be some time taken by sending the command and reading the EPC back but it seems like a loot to me.
Is it something people have witnessed too? Is it due to the wrapper or even if I were to switch to the C API I would have the same issue? Thanks for your help

**Comment by gotthardp** [comment]
Hello. There may be also some time required to start/stop the reading. The machine may be busy with some activities between the reads. It likely not related to the wrapper, but it may be related to Python (e.g. garbage collecting). After all, it's not a real-time system so precise timing is not guaranteed.
