### ISSUE TITLE
Aftering installing in ubuntu not working

### ISSUE THREAD

**Issue by peinfant54** [gotthardp/python-mercuryapi#78]
Hi, I'm a little lost here. I did the installing with the make file (i have a few missing libraries, but I was be able to install them without a problem). So the installation was fine, but when I tried to execute the setup.py file i get this:

./setup.py: 7: ./setup.py: Syntax error: "(" unexpected

I did a test file with the example that you have in the Readme File, but when I executed, i get:

./texxt.py: línea 2: error sintáctico cerca del elemento inesperado `('

What I'm doing wrong?

Thanks

**Comment by gotthardp** [comment]
Hello. How do you execute the scripts? Have a look into the documentation to see how the scripts should be started.

**Comment by gotthardp** [comment]
Did you solve the issue? May I close the ticket?

**Comment by peinfant54** [comment]
Hi, sorry....Yes I solve the issue....I guess some libraries were corrupt o something, because I uninstall everything and start over and the work without a problem....

Thanks

**Comment by gotthardp** [comment]
Cool. Thanks!
