### ISSUE TITLE
read_tag_memory function not working

### ISSUE THREAD

**Issue by ACB2231** [gotthardp/python-mercuryapi#79]
Hello,

When I use the "read_tag_memory" function almost always returns "None" (unless the tag is held directly in front of the antenna) even though I can clearly read the same tags when using a different read function.

Could it be that the "read_tag_memory" function is set to read with a lower power?

Thank you for your help.

**Comment by gotthardp** [comment]
`read_tag_memory` definitely does **not** use whatever you defined in `set_read_plan`. The `set_read_powers` could work.

**Comment by gotthardp** [comment]
Hello. Did you manage to solve the issue?

**Comment by ACB2231** [comment]
Yes thank you for your help, set_read_powers worked.
