### ISSUE TITLE
How to identify which TTY device is connected to?

### ISSUE THREAD

**Issue by Tasty213** [gotthardp/python-mercuryapi#80]
I'm trying to set up the API on a raspberry pi but can't work out which TTY the device is connected to. When i run the sample code it complains tha ti can't find /dev/ttyUSB0

Thanks

**Comment by gotthardp** [comment]
This is a general Linux problem.
After plugging it in you can review the `dmesg` log, or you can check which device appeared after you plugged it in
```bash
ls -1 /dev > dev.txt

ls -1 /dev > dev2.txt
diff dev.txt dev2.txt
```
Or you can fix the name as explained in several tutorials, e.g. here: https://www.freva.com/2019/06/20/assign-fixed-usb-port-names-to-your-raspberry-pi/
