### ISSUE TITLE
tag.timestamp returns wrong time

### ISSUE THREAD

**Issue by Tasty213** [gotthardp/python-mercuryapi#81]
I'm to trying to use `tag.timestamp` to log when tags where read, however it returns a number that is far too small. Below is a sample of the data i've collected so far.

```python
print('\n',df[::1750])
>>> 
```
Index |                  EPC                        | Phase | RSSI | Power | Frequency | Time
-------|--------------------------------|-------|------|--------|-------------|-------
0         | b'E280689400004001BB14307B'   | 174  | -34  |  100   |  866300 |  2944282.049
1750   | b'E280689400004001BB143081'   | 171  | -50  |  1600 |  866900 |  2951591.757
3500   | b'E280689400004001BB143081'   | 174  | -46  |  2500 |  866300 |  2944212.048
5250   | b'300833B2DDD9014000000019' | 174  | -41  |  1200 |  866300 |  2951520.398
7000   | b'300833B2DDD9014000000010' | 174  | -38  |  1900 |  866900 |  2952787.685
8750   | b'E280689400004001BB14307B'   | 174  | -29  |  2500 |  865700 |  2986322.925
10500 | b'E280689400004001BB14307B'   | 174  | -38  |  1000 |  866900 |  2976850.157
12250 | b'300833B2DDD9014000000010' | 174  | -38  |  1800 |  865700 |  2977857.898
14000 | b'E280689400004001BB143081'   | 171  | -53  |  2500 |  866300 |  2985154.444
15750 | b'E280689400004001BB14307B'   | 174  | -38  |  800   |  867500 |  3018695.065
17500 | b'300833B2DDD9014000000019' |  174 | -40  |  1600 |   866300 |  3019702.707

If you convert one of times with the recommended datetime function
```python
dt.utcfromtimestamp(2944282.049)
>>> datetime.datetime(1970, 2, 4, 1, 51, 22, 49000)
```
I've double checked on the pi and it's time is correct. I presume I've jut misunderstood how to convert the time but i can't see how.

How do I get the correct time?

**Comment by gotthardp** [comment]
It is my fault, sorry. I should have tested this.

I made (and tested) a fix, so it should work now.
