### ISSUE TITLE
Freeing up Connection / Destroy Reader Object Method

### ISSUE THREAD

**Issue by Chikenbagelz** [gotthardp/python-mercuryapi#84]
First of all let me thank you for all of your hard work creating this Python wrapper, it is amazing work Petr. My question is if there is a wrapped method for the destroy() method in the original C code to destroy the reader object and free up the connection? Thank you again for all of your work and I apologize if I just missed it.

**Comment by gotthardp** [comment]
Hello. Python has reference-counters and frees objects automatically when not needed, so the destroy method is called when (Python decides) the object is no longer needed.

**Comment by Chikenbagelz** [comment]
Perfect, thank you so much!
