### ISSUE TITLE
Phase measurements

### ISSUE THREAD

**Issue by emilesabatier** [gotthardp/python-mercuryapi#87]
Hi,

I would like to know why when we get the phase from TagData, it's scaled between 0 and pi and not between 0 and 2*pi ? Is it from the wrapper ?

Thanks

**Comment by gotthardp** [comment]
The wraper does not process the phase in any way. I doublechecked the data type-- and it is correct. It must come from the reader itself.

**Comment by emilesabatier** [comment]
Ok thanks :)
